# Truba

Ders kapsamında TRUBA sunucularını kullanacağız. Bu imkanı bize sundukları için teşekkür ederiz.

Öncelikle [TRUBA](https://docs.truba.gov.tr/index.html) internet sitesine giderek sistemi inceleyelim.

TRUBA kaynaklarına üniversite içerisinden rahatlıkla bağlanabilirsiniz, ancak üniversite dışından bağlanmak için ise bilgisayarınza OpenVPN programını kurmanız gerekmektedir. 

Ayrıntılar için [Kurulum kılavuzunu](https://docs.truba.gov.tr/TRUBA/kullanici-el-kitabi/open-vpn/index.html) inceleyin ve bilgisayarınza uygun olan kılavuz ile OpenVPN kurulumunu tamamlayınız.

Kurulum tamamlandıktan sonra, TRUBA tarafından size gönderilen kullanıcı ismi ve şifreniz ile, OpenVPN sistemine bağlanmanız gerekmektedir. Ardından, mobaxterm ile TRUBA sistemine bağlanabiliriz.

Normalde uzak bir bilgisyara bağlanma sürecini şöyle özetleyebiliriz. İnternet üzerinde, sizin bilgisyarınız ve uzak bilgisayar arasında şifreli bir tünel (`ssh`) bağlantısı kurulmaktadır. Bunu @fig-graph-1'de rahatlıkla görebiliriz. Bu şekilde yapılan bir bağlantıda, TRUBA sistemine şifreli bir tünel açılmaktadır.

```{dot}
// | label: fig-graph-1
// | fig-cap: "ULAKBİM ağı içerisinden, TRUBA'ya doğrudan `ssh` bağlantısı kurabilirsiniz."
// | fig-width: 200px
// | fig-height: 200px

digraph g{
    rankdir = "BT";
    node [shape = "rect"];
    "Yerel Bilgisayar" -> "TRUBA";
}
```

Ancak, ULAKBİM üzerinden yapılmayan bağlantılar güvenli olmayabir. Bu tip bilgisayar sistemleri yoğunlukla saldırı altındadır. Bu yüzden güvenli bir bağlantı oluşturmak için farklı yöntemler kullanılabilir. Bazı sunucu sistemleri iki faktörlü doğrulama kullanırken, TRUBA sistemi, ULAKBİM dışındaki bağlantılarda öncelikle sanal ağa bağlanmanızı zorunlu tutmaktadır. Bağlantı güvenliği için öncelikle OpenVPN ile sanal ağa, oradan da TRUBA'ya bağlanıyoruz (@fig-graph-2).

```{dot}
// | label: fig-graph-2
// | fig-cap: "Üniversite ağı dışından yapacağınız bağlantılarda öncelikle OpenVPN üzerinde ULAKBİM sanal ağına bağlanmalısınız."
// | fig-width: 200px
// | fig-height: 200px

digraph g{
    rankdir = "BT";
    node [shape = "rect"];
    "Yerel Bilgisayar" -> "OpenVPN" -> "TRUBA";
}
```
