# Önsöz {.unnumbered}

Merhabalar! Lisans üstü seviyede verilen **İleri Biyoinformatik** dersine hoşgeldiniz!

## Ders hakkında ön bilgi

Dersimiz çoğunlukla yüz yüze işlenecektir. Ancak akademik programıma bağlı olarak çevrimiçi işleme opsiyonunu da kullanacağız. 

Ders kapsamında Mersin Üniversitesi Fen Fakültesi 30 kişilik bilgisayar laboratuvarını kullanacağız.

## Dersin işlenme yöntemi

Ders kapsamında Türkiye Ulusal e-Bilişim Altyapısı'nın (TRUBA) yüksek başarımlı bilgisayar sistemlerini kullanacağız. Bu imkanı bize sağlayarak, öğrencilere eğitim hesapları açtıkları için teşekkür ederiz.

## Konular

Altyapı kısmı, TRUBA sistemine nasıl bağlanılacağı, komutların kullanımı ve TRUBA sisteminde iş göndermek için gerekli betiklerin tanıtımına ayrılmıştır.

Birinci kısımda genel olarak TRUBA sistemi ve komut satırı üzerine bilgiler verlecektir. @sec-truba, TRUBA sisteminin tanıtımını ve sisteme nasıl bağlanacağımız hakkında gerekli bilgileri içermektedir. Daha sonra @sec-command-line kısmında ise, TRUBA sisteminin ve linux komut satırının kullanımı hakkında gerekli bilgiler ve pratikler verilmiştir. 

İkinci kısımda ise, kullanılacak verinin niteliği, bu verinin yeni Nesil dizileme teknolojileri ile eldesi, saklanması ve en sonunda da elde edilmesi anlatılacaktır.

Üçüncü kısımda ise DNA hizalama ve varyant çağırma üzerine temel bilgiler aktarılmıştır.

Dördüncü kısımda Metagenomik yöntemler irdelencektir.

Beşinci kısımda filogenetik 

Altıncı kısımda ise RNA dizleme ve bu verinin analizi anlatılacaktır.

