# Fastq kalite kontrol

İlk olarak fastq dosyalarının kalite kontrolünü işleyeceğiz.

Öncelikle TRUBA sistemimize girelim.

```bash
ssh egitim@levrek.ulakbim.gov.tr
```

Şimdi `Lectures` klasörünü ve projemizin klasörün oluşturalım:

```bash
mkdir -p Lectures
cd Lectures
mkdir 00-Quality-Control
cd 00-Quality-Control
```

Her projede temel klasörler olmalı. Ham veriler, betikler, sonuçlar, tarihçeler ve conda çevreleri hep belli yerlerde olmalı:

```bash
mkdir data
mkdir logs
mkdir scripts
mkdir containers
```

Kullanacağımız konteyner imajlarını indirelim. Bunu sizin yapmanıza gerek yok, aşağıdaki klasörde imajı görebilirsiniz:

```bash
ls /arf/home/egitimg14/Projects/Lectures/00-Quality-Control/containers/
```

İmajları aşağıdaki şekilde indirebilirsiniz, ancak şu anda yapmanıza gerek yok:

```bash
cd containers
singularity pull https://depot.galaxyproject.org/singularity/fastqc:0.12.1--hdfd78af_0
singularity pull https://depot.galaxyproject.org/singularity/cutadapt:5.0--py39hbcbf7aa_0
cd ..
```

Şimdi de kullanacağımız örnek veriyi indirelim:

```bash
wget ftp.sra.ebi.ac.uk/vol1/fastq/SRR702/004/SRR7029604/SRR7029604.fastq.gz -P data/
wget ftp.sra.ebi.ac.uk/vol1/fastq/SRR740/005/SRR7405885/SRR7405885_1.fastq.gz -P data/
wget ftp.sra.ebi.ac.uk/vol1/fastq/SRR740/005/SRR7405885/SRR7405885_2.fastq.gz -P data/
```

## Ham okumaların kalite kontrolü

Bu iş için kullanacağımız betiği indirelim:

```bash
wget https://raw.githubusercontent.com/emrahkirdok/bioinformatics/refs/heads/main/09-scripts/02-sbatch-scripts/fastqc-before-trimming.sh -P scripts/
```

Klasörü kontrol edelim:

```bash
ls -ltrh scripts
```

Şimdi de işimizi gönderelim:

```bash
sbatch scripts/fastqc-before-trimming.sh
```

## Tek yönlü ham okumaların işlenmesi

Kullanacağımız betiği indirelim:

```bash
wget https://raw.githubusercontent.com/emrahkirdok/bioinformatics/refs/heads/main/09-scripts/02-sbatch-scripts/cutadapt-adapter-trimming-se.sh -P scripts/
```

Şimdi betiğimizi çalıştıralım:

```bash
sbatch scripts/cutadapt-adapter-trimming-se.sh
```

Kontrol edelim:

```bash
squeue
```

## Çift yönlü ham okumaların işlenmesi

```bash
wget https://raw.githubusercontent.com/emrahkirdok/bioinformatics/refs/heads/main/09-scripts/02-sbatch-scripts/cutadapt-adapter-trimming-pe.sh -P scripts/
```

Şimdi betiğimizi çalıştıralım:

```bash
sbatch scripts/cutadapt-adapter-trimming-pe.sh
```

Kontrol edelim:

```bash
squeue
```

## Cutadapt parametreleri

Şimdi `cutadapt --help` komutu ile programın bütün opsiyonlarını öğrenebilirisniz. Ancak en önemlililer aşağıda:

+ `a`: ileri yönlü DNA okumalarında adaptörlerin kesilmesi
+ `A`: geri yönlü okumalardaki adaptörlerin kesilmesi
+ `q`: belirlenen eşik değerinin altındaki okuma kalitesine sahip nükleotidlerin kesilmesi
+ `minimum-length` kesimin ardından belirli nükleotidleriden kısa olan okumaları at

Bunun için Barbun isimli bilgisayardan, 4 tane işlemci rezerve ediyoruz ve egitim kullanıcı ismiyle işimizi slurm sistemine gönderityoruz.

Bu iş dosyasını inceleyelim

Birinci satır genelde zorunlu olarak kullanılması gereken bir satır. Bu aslında dosyanın `bash` ile çalıştırılması gerektiğini söylüyor:

```bash
#!/bin/bash
```

`#SBATCH` ile başlayan satırlar ise, slurm sisteminde gerekli olan parametreleri belirliyor.

+ `--partition` opsiyonu ile kullanacağımız bilgisayarı belirleyebiliriyoruz
+ `--ntasks-per-node` opsyinu ile kaç tane çekirdek kullanmak istediğimizi belirliyoruz
+ `--user` opsiyonu ise kullancı ismimizi belirlememizi sağlıyor. Unutmayıni kullanıcı isminizi mutlaka belirlemeliziniz.

`PATH` ile başlayan satır ise, kullanılacak programların yolunu belirtiyor.

Ardından ilk olarak `mkdir` ile çıktı dosyalarımızı yazacağımız klasörü belirliyoruz.

Daha sonra `fastqc` programını çalıştırıyoruz.

Öncelile kullanıcı isminizi `nano` programı ile düzeltiniz:

```bash
nano fastqc_before_trimming.sh
```

İş dosyasını çalıştıralım:

```bash
sbatch fastqc_before_trimming.sh
```

Gönderdiğimiz işi şu şekilde kontrol edelim:

```bash
squeue -u egitim
```

Bunu ara ara takip edelim. İşimiz bittiğinide artık bu ekranda bir bilgi olmayacak.

İşimiz bittiğinde sonra, çalışma klasörümüzde `slurm` ile başlayan bir dosya oluşacak. Bu dosyayı, `less` programı ile kontrol edelim. Bu doya bizim komutlarımızn çıktılarını gösterecek.

Eğer başarılı olduysak `results/fastqc_before_trimming` klasörü içinde bir kaç dosya oluşacak. Onlara bakalım:

```bash
ls -lh results/fastqc_before_trimming
```

