# RNA Dizileme

Bu proje kapsamında, RNA dizileme veri analizi çalışması yapılacaktır. Projeyi aşağıdaki şekilde şematize edebiliriz (@fig-graph-4):

```{dot}
// | label: fig-graph-3
// | fig-cap: "RNA dizileme veri analizi şeması"
// | fig-width: 200px
// | fig-height: 200px

digraph g{
    rankdir = "BT";
    node [shape = "rect"];
    "Ham Fastq Dosyaları" -> "Ön İşlem" -> "İşlenmiş Fastq dosyaları" -> "Referans Genoma\nHizalama" -> "Sam ve Bam\ndosyaları Eldesi" -> "DNA sayı matrisi";
    "Referans Genom" -> "Referans Genoma\nHizalama";
}
```

## Klasör kurulumu

Öncelikle çalışma klasörümüze gelip, yeni bir proje alanı oluşturalım:

```bash
cd
cd Lectures
mkdir 02-RNASeq; cd 02-RNASeq
```

Şimdi de gerekli klasörleri oluşturalım:

```bash
mkdir -p data/fastq
mkdir -p data/ref
mkdir logs
mkdir envs
mkdir scripts
``` 

Conda programını aktive edelim:

```bash
eval "$(/truba/home/$USER/miniconda3/bin/conda shell.bash hook)"
```

Konda çevresini kuralım ve aktive edelim:

```bash
wget https://raw.githubusercontent.com/emrahkirdok/bioinformatics/refs/heads/main/09-scripts/01-environments/rnaseq.yaml -P envs/

conda env create --file envs/rnaseq.yaml
conda activate rnasea
```

Çalışmamızda kullanacağımız *Pseudomonas putida KT2440* referans genomunu alalım:

```bash
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/007/565/GCA_000007565.2_ASM756v2/GCA_000007565.2_ASM756v2_genomic.fna.gz -P data/ref

gunzip data/ref/GCA_000007565.2_ASM756v2_genomic.fna.gz

wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/007/565/GCA_000007565.2_ASM756v2/GCA_000007565.2_ASM756v2_genomic.gtf.gz -P data/ref

gunzip data/ref/GCA_000007565.2_ASM756v2_genomic.gtf.gz
```

Şimdi de okumaları alalım:

```bash
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR702/005/SRR7029605/SRR7029605.fastq.gz -P data/fastq
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR702/007/SRR7029607/SRR7029607.fastq.gz -P data/fastq
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR740/006/SRR7405886/SRR7405886.fastq.gz -P data/fastq
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR740/007/SRR7405887/SRR7405887.fastq.gz -P data/fastq

```

## Kalite kontrol

Bütün işlemler her zaman kalite kontrol ile başlamalı. Bu yüzden öncelikle bir kalite kontrol adımı uygylayacağız.

```bash
wget https://raw.githubusercontent.com/emrahkirdok/bioinformatics/refs/heads/main/09-scripts/02-sbatch-scripts/quality-control-and-cutadapt.sh -P scripts/
```

## RNAseq hizalama

Önce genomu indeksleyelim:

```bash
bowtie2-build data/ref/GCA_000007565.2_ASM756v2_genomic.fna data/ref/GCA_000007565.2_ASM756v2_genomic.fna
```

Şimdi de okumalarımız referans genoma hizalayalım. Dikkat edin elimizde 4 tane okuma var, yani dört farklı iş göndermeliyiz. Önce betiği indirelim:

```bash
wget https://raw.githubusercontent.com/emrahkirdok/bioinformatics/refs/heads/main/09-scripts/02-sbatch-scripts/rnaseq-alignment.sh -P scripts/
```

Şimdi de betiği gönderelim:

```bash
sbatch scripts/rnaseq-alignment.sh
```

Dikkat edin elimizde 4 tane var, hepsi için dosyayı değiştirmeliyiz, ya da betiği parametre ile yeniden düzenlemeliyiz:


Dosyayı kopyalalayım:

```bash
cp scripts/rnaseq-alignment.sh scripts/rnaseq-alignment-parameter.sh
```

Şimdi de komut satırı parametresi işlevi ekleyelim:

```bash
cp scripts/rnaseq-alignment.sh scripts/rnaseq-alignment-command-line-parameter.sh
```

Son olarak dosyalardan bir tanesini `samtools tview` ile inceleyelim.

Şimdi, `featureCounts` programı ile, her gene karşılık gelen DNA okuması miktarını alalım. Ama bunun betiğini siz yazın:

```bash
mkdir -p results/counts

featureCounts -T4 -t CDS -a data/ref/GCA_000007565.2_ASM756v2_genomic.fna -o results/counts/counts-SRR7029605.txt results/alignment/SRR7029605.sorted.bam
```
